### ISSUE TITLE
SQLSTATE[42S22]: Column not found: UserCoreModel.php

### ISSUE THREAD

**Issue by willsha101** [pH7Software/pH7-Social-Dating-CMS#1119]
**Just installed it and was setting it up, and all of a sudden I'm logged out, now I can't log back into admin, I have managed to set it to development mode manually**

I'm on Godaddy hosting I've used the Cpanel installer.

Message:	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profileId' in 'field list'
File:	/home/w11220427/public_html/findvirgins.com/_protected/app/system/core/models/UserCoreModel.php
Line:	1254

Trace:
#0 /home/w11220427/public_html/findvirgins.com/_protected/app/system/core/models/UserCoreModel.php(1254): PDOStatement->execute()
#1 /home/w11220427/public_html/findvirgins.com/_protected/app/system/core/classes/SecurityCore.php(70): PH7\UserCoreModel->getId()
#2 /home/w11220427/public_html/findvirgins.com/_protected/app/system/core/classes/SecurityCore.php(36): PH7\SecurityCore->getUserFirstNameFromEmail()
#3 /home/w11220427/public_html/findvirgins.com/_protected/framework/Mvc/Model/Security.class.php(160): PH7\SecurityCore->sendLoginAttemptsExceededAlert()
#4 /home/w11220427/public_html/findvirgins.com/_protected/app/system/modules/admin123/forms/processing/LoginFormProcess.php(51): PH7\Framework\Mvc\Model\Security->checkLoginAttempt()
#5 /home/w11220427/public_html/findvirgins.com/_protected/app/system/modules/admin123/forms/LoginForm.php(32): PH7\LoginFormProcess->__construct()
#6 /home/w11220427/public_html/findvirgins.com/_protected/data/cache/pH7tpl_compile/admin123_0deb11e29b9ce57d374c18493fc8906e/base/main/login.cpl.php(15): PH7\LoginForm::display()
#7 /home/w11220427/public_html/findvirgins.com/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(358): require('/home/w11220427...')
#8 /home/w11220427/public_html/findvirgins.com/_protected/data/cache/pH7tpl_compile/public_main/base/layout.cpl.phplayout.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display()
#9 /home/w11220427/public_html/findvirgins.com/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(358): require('/home/w11220427...')
#10 /home/w11220427/public_html/findvirgins.com/_protected/framework/Mvc/Controller/Controller.class.php(85): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display()
#11 /home/w11220427/public_html/findvirgins.com/_protected/app/system/modules/admin123/controllers/MainController.php(69): PH7\Framework\Mvc\Controller\Controller->output()
#12 [internal function]: PH7\MainController->login()
#13 /home/w11220427/public_html/findvirgins.com/_protected/framework/Mvc/Router/FrontController.class.php(656): ReflectionMethod->invokeArgs()
#14 /home/w11220427/public_html/findvirgins.com/_protected/framework/Mvc/Router/FrontController.class.php(615): PH7\Framework\Mvc\Router\FrontController->runController()
#15 /home/w11220427/public_html/findvirgins.com/_protected/app/Bootstrap.php(92): PH7\Framework\Mvc\Router\FrontController->runRouter()
#16 /home/w11220427/public_html/findvirgins.com/index.php(45): PH7\Bootstrap->run()
#17 {main}

**Screenshots / Screencasts**

(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)
![Screenshot 2023-06-05 021941](https://github.com/pH7Software/pH7-Social-Dating-CMS/assets/45546070/0e3b619b-a96e-4692-81bd-5394d40289ee)

**Comment by pH-7** [comment]
Thanks very much for mentioning this @willsha101. Although it's the first time someone reports this error,  I will have a look at it.

**Comment by pH-7** [comment]
The problem shouldn't happen anymore. Thank you for your patience!
