### ISSUE TITLE
Error on Admin Client Login View Mail from @Admin

### ISSUE THREAD

**Issue by tturbo4gg** [pH7Software/pH7-Social-Dating-CMS#1140]
**Describe the bug**

(a clear and concise description of what the bug is.)

**To Reproduce**

1. Go to 'http://mysite.com/admin123/user/browse'
2. Click on Login.'
3. Scroll down to 'Messages -> Inbox' http://mysite.com/mail

`C:\xampp\htdocs\_protected\framework\Layout\Html\Design.class.php on line 627

Fatal error: Uncaught TypeError: PH7\PH2Gravatar\Image::get(): Argument #1 ($email) must be of type string, bool given, called in C:\xampp\htdocs\_protected\framework\Layout\Html\Design.class.php on line 647 and defined in C:\xampp\htdocs\_protected\vendor\ph-7\ph2gravatar\src\Image.php:19 Stack trace: #0 C:\xampp\htdocs\_protected\framework\Layout\Html\Design.class.php(647): PH7\PH2Gravatar\Image::get(false, Array) #1 C:\xampp\htdocs\_protected\framework\Layout\Html\Design.class.php(661): PH7\Framework\Layout\Html\Design->PH7\Framework\Layout\Html\{closure}() #2 C:\xampp\htdocs\_protected\app\system\core\classes\design\AvatarDesignCore.php(61): PH7\Framework\Layout\Html\Design->getUserAvatar('admin', 'admin', 32) #3 C:\xampp\htdocs\_protected\data\cache\pH7tpl_compile\mail_238e310d37ca82cd472e80cbdd56973d\base\main\list.inc.cpl.php(15): PH7\AvatarDesignCore->get('admin', 'Administrator', 'admin', 32) #4 C:\xampp\htdocs\_protected\framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl.class.php(353): require('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\_protected\data\cache\pH7tpl_compile\mail_238e310d37ca82cd472e80cbdd56973d\base\main\msglist.inc.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('list.inc.tpl') #6 C:\xampp\htdocs\_protected\framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl.class.php(353): require('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\_protected\data\cache\pH7tpl_compile\mail_238e310d37ca82cd472e80cbdd56973d\base\main\layout.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('main\\msglist.in...', 'C:\\xampp\\htdocs...') #8 C:\xampp\htdocs\_protected\framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl.class.php(353): require('C:\\xampp\\htdocs...') #9 C:\xampp\htdocs\_protected\data\cache\pH7tpl_compile\public_main\zendate\layout.cpl.phplayout.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', 'C:\\xampp\\htdocs...') #10 C:\xampp\htdocs\_protected\framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl.class.php(353): require('C:\\xampp\\htdocs...') #11 C:\xampp\htdocs\_protected\framework\Mvc\Controller\Controller.class.php(85): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', 'C:\\xampp\\htdocs...') #12 C:\xampp\htdocs\_protected\app\system\modules\mail\controllers\MainController.php(146): PH7\Framework\Mvc\Controller\Controller->output() #13 [internal function]: PH7\MainController->inbox() #14 C:\xampp\htdocs\_protected\framework\Mvc\Router\FrontController.class.php(656): ReflectionMethod->invokeArgs(Object(PH7\MainController), Array) #15 C:\xampp\htdocs\_protected\framework\Mvc\Router\FrontController.class.php(615): PH7\Framework\Mvc\Router\FrontController->runController() #16 C:\xampp\htdocs\_protected\app\Bootstrap.php(92): PH7\Framework\Mvc\Router\FrontController->runRouter() #17 C:\xampp\htdocs\index.php(45): PH7\Bootstrap->run() #18 {main} thrown in C:\xampp\htdocs\_protected\vendor\ph-7\ph2gravatar\src\Image.php on line 19`

**Expected Behavior**

(a clear and concise description of what you expected to happen.)

**Screenshots / Screencasts**
![image](https://github.com/pH7Software/pH7-Social-Dating-CMS/assets/147652145/b3c2174c-9af9-4776-b47d-6f882d1cb5c7)

(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)

**Comment by STProgrammer** [comment]
It's just me, or this CMS is full of bugs and doesn't work?

1) When I login into admin dashboard, it changes password, which causes you can't login again. I fixed this and sent pull requiest, which is not accepted yet.

2) I can't login is normal user. When I login, I'm just redirected to same login page, and it seems like I'm not logged in yet.

I can't even login to test it. It seems like it's full of bugs.

**Comment by AleksKorsun** [comment]
Добрый день. Я не могу войти в панель администратора, хотя пароль правильный. Какие есть пути решения этой проблемы

**Comment by pH-7** [comment]
Thanks very much. I will have a look at it and will fix it (if needed) in the next upcoming version.

Thanks again for reporting this issue.
