### ISSUE TITLE
Installation Issue with Version 18 and _protected/framework/Server/Server.class.php

### ISSUE THREAD

**Issue by nootkan** [pH7Software/pH7-Social-Dating-CMS#1149]
**Describe the bug**

(a clear and concise description of what the bug is.)
After manually installing version 18 or 17.9.1 as it is called using filezilla sftp, I get a 500 error when clicking on the link in the success page after installation. 

AlmaLinux v8.9.0 STANDARD
cPanel Version 116.0.11
Apache Version    2.4.58
Php version      8.0 also tried with 8.1 with the same result
MySQL Version    8.0.36
Architecture    x86_64
Kernel Version    4.18.0-477.27.2.el8_8.x86_64

Tried to comment out line 164 in Server.class.php as per a [previous issue](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/1062) which worked for that poster but it didn't work for me.

**To Reproduce**

1. Go to mydomain.com
2. Click on nothing 
3. Scroll down to nothing
4. See error After manually changing production to development in the config.ini file and refreshing the page I see this error and stack trace: 

Fatal error: Uncaught Error: Class "PH7\Framework\Security\Version" not found in /home/mydomain/public_html/_protected/framework/Server/Server.class.php:65 

Stack trace: 
#0 /home/mydomain/public_html/_protected/app/Bootstrap.php(86): PH7\Framework\Server\Server->__construct() 
#1 /home/mydomain/public_html/index.php(45): PH7\Bootstrap->run() 
#2 {main} thrown in /home/mydomain/public_html/_protected/framework/Server/Server.class.php on line 65

**Expected Behavior**

I expect to be taken to my webpage front end and backend so I can get started customizing.

**Screenshots / Screencasts**
none to provide as error provided above.
(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)

**Comment by pH-7** [comment]
Now fixed! Thanks for your patience. A new upcoming version (v18.2.0) is will be released quite soon too! Stayed tuned!
