### ISSUE TITLE
Block Countries bugged?

### ISSUE THREAD

**Issue by zeerprettiggestoord** [pH7Software/pH7-Social-Dating-CMS#212]
Hi, again toying around in the admin panel.
Like the curious man I am, I clicked the Block Countries link.
I received an error. So setting it to development mode to get the debug info I got this:

 

Message: | /home/gerrizk257/domains/lucky-you.nl/_protected/app/system/modules/admin123/views/base/tpl/tool/blockcountry.tpl file does no exist.
-- | --
File: | /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php
Line: | 499
Trace: | #0 /home/gerrizk257/domains/lucky-you.nl/_protected/data/cache/pH7tpl_compile/admin123_cb0e8a7590831e248d6c4a50be928211/base/toollayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('tool/blockcount...', '/home/gerrizk25...') #1 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(518): require('/home/gerrizk25...') #2 /home/gerrizk257/domains/lucky-you.nl/_protected/data/cache/pH7tpl_compile/public_main/datelove/layout.cpl.phplayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/gerrizk25...') #3 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(518): require('/home/gerrizk25...') #4 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Mvc/Controller/Controller.class.php(82): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/gerrizk25...') #5 /home/gerrizk257/domains/lucky-you.nl/_protected/app/system/modules/admin123/controllers/ToolController.php(115): PH7\Framework\Mvc\Controller\Controller->output() #6 [internal function]: PH7\ToolController->blockCountry() #7 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Mvc/Router/FrontController.class.php(566): ReflectionMethod->invokeArgs(Object(PH7\ToolController), Array) #8 /home/gerrizk257/domains/lucky-you.nl/_protected/app/Bootstrap.php(99): PH7\Framework\Mvc\Router\FrontController->runRouter() #9 /home/gerrizk257/domains/lucky-you.nl/public_html/index.php(46): PH7\Bootstrap->run() #10 {main}

This installation was downloaded from soundforge

**Comment by zeerprettiggestoord** [comment]
I remembered seeing a notification that you guys were working on it.
So I downloaded the file that is missing from github and uploaded it to the website.
Now I get the countries list.
