### ISSUE TITLE
After cleare installiation main page and admin page not working

### ISSUE THREAD

**Issue by berefe** [pH7Software/pH7-Social-Dating-CMS#423]
Hi,
Windows 10 , apache with XAMPP control panel v3.2.2
After Installation (newest version ) on http://localhost/pH7Builder-14.8.9/ completed successfully. main page and admin page can't reachable. it says Please sign in first.

Error:
My Dating WebApp
Please sign in first 😉
Internal Server Error
The server encountered an error. This is most often caused by a scripting problem, a failed database accessattempt, or other similar reasons. 
If you are the administrator of the site, please go to your admin panel -> Tools -> Environment Mode and set to"Development", then go back here to see the details of the error. 
Big thanks to pH7CMS❤️ 

2. issue:
also after development mode set manuel in config.ini main page and login page gets error.
http://localhost/pH7Builder-14.8.9/admin123/main/login 

Error: Parsing code unset!

![image](https://user-images.githubusercontent.com/47064355/51791386-eedee580-2156-11e9-8757-a6a992ccbc6d.png)

![image](https://user-images.githubusercontent.com/47064355/51791396-103fd180-2157-11e9-842c-1f37a404e3d4.png)

Message: | Parsing code unset!
-- | --
File: | C:\xampp\htdocs\pH7Builder-14.8.9\_protected\framework\Layout\Tpl\Engine\PH7Tpl\Syntax\Curly.class.php
Line: | 25
Trace: | #0 C:\xampp\htdocs\pH7Builder-14.8.9\_protected\framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl.class.php(726): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\Syntax\Curly->parse() #1 C:\xampp\htdocs\pH7Builder-14.8.9\_protected\framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl.class.php(672): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->parse() #2 C:\xampp\htdocs\pH7Builder-14.8.9\_protected\framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl.class.php(350): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->compile() #3 C:\xampp\htdocs\pH7Builder-14.8.9\_protected\framework\Mvc\Controller\Controller.class.php(83): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', 'C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\pH7Builder-14.8.9\_protected\app\system\modules\admin123\controllers\MainController.php(68): PH7\Framework\Mvc\Controller\Controller->output() #5 [internal function]: PH7\MainController->login() #6 C:\xampp\htdocs\pH7Builder-14.8.9\_protected\framework\Mvc\Router\FrontController.class.php(640): ReflectionMethod->invokeArgs(Object(PH7\MainController), Array) #7 C:\xampp\htdocs\pH7Builder-14.8.9\_protected\framework\Mvc\Router\FrontController.class.php(598): PH7\Framework\Mvc\Router\FrontController->runController() #8 C:\xampp\htdocs\pH7Builder-14.8.9\_protected\app\Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter() #9 C:\xampp\htdocs\pH7Builder-14.8.9\index.php(46): PH7\Bootstrap->run() #10 {main}

**Comment by berefe** [comment]
Thanks fast replay and helps. 
Solved.
